import os

os.environ["AWS_ACCESS_KEY_ID"] = os.getenv("CONFIG_STORAGE_ACCESS_KEY")
os.environ["AWS_SECRET_ACCESS_KEY"] = os.getenv("CONFIG_STORAGE_SECRET_KEY")
os.environ["AWS_S3_BUCKET"] = os.getenv("CONFIG_STORAGE_NAME")
os.environ["S3_METADATA_BUCKET"] = os.getenv("CONFIG_STORAGE_NAME")
os.environ["AWS_REGION"] = os.getenv("CONFIG_STORAGE_REGION") + "-1"

class Config:
    DATA_INPUT_STORAGE_ACCESS_KEY = os.getenv("DATA_INPUT_STORAGE_ACCESS_KEY")
    DATA_INPUT_STORAGE_SECRET_KEY = os.getenv("DATA_INPUT_STORAGE_SECRET_KEY")
    DATA_INPUT_STORAGE_REGION = os.getenv("DATA_INPUT_STORAGE_REGION")
    DATA_INPUT_STORAGE_NAME = os.getenv("DATA_INPUT_STORAGE_NAME")
    DATA_OUTPUT_STORAGE_ACCESS_KEY = os.getenv("DATA_OUTPUT_STORAGE_ACCESS_KEY")
    DATA_OUTPUT_STORAGE_SECRET_KEY = os.getenv("DATA_OUTPUT_STORAGE_SECRET_KEY")
    DATA_OUTPUT_STORAGE_REGION = os.getenv("DATA_OUTPUT_STORAGE_REGION")
    DATA_OUTPUT_STORAGE_NAME = os.getenv("DATA_OUTPUT_STORAGE_NAME")
    CONFIG_STORAGE_ACCESS_KEY = os.getenv("CONFIG_STORAGE_ACCESS_KEY")
    CONFIG_STORAGE_SECRET_KEY = os.getenv("CONFIG_STORAGE_SECRET_KEY")
    CONFIG_STORAGE_REGION = os.getenv("CONFIG_STORAGE_REGION")
    CONFIG_STORAGE_NAME = os.getenv("CONFIG_STORAGE_NAME")
