apiVersion: v1
kind: Service
metadata:
  name: aggregation-service
  labels:
    app: aggregation-service
spec:
  type: ClusterIP
  selector:
    app: aggregation-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
