import os


class Config:
    DATA_INPUT_STORAGE_ACCESS_KEY = os.getenv("DATA_INPUT_STORAGE_ACCESS_KEY")
    DATA_INPUT_STORAGE_SECRET_KEY = os.getenv("DATA_INPUT_STORAGE_SECRET_KEY")
    DATA_INPUT_STORAGE_REGION = os.getenv("DATA_INPUT_STORAGE_REGION")
    DATA_INPUT_STORAGE_NAME = os.getenv("DATA_INPUT_STORAGE_NAME")
    MONITOR_STORAGE_ACCESS_KEY = os.getenv("MONITOR_STORAGE_ACCESS_KEY")
    MONITOR_STORAGE_SECRET_KEY = os.getenv("MONITOR_STORAGE_SECRET_KEY")
    MONITOR_STORAGE_REGION = os.getenv("MONITOR_STORAGE_REGION")
    MONITOR_STORAGE_NAME = os.getenv("MONITOR_STORAGE_NAME")
